GET http://localhost:3001/users HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3001/users HTTP/1.1
content-type: application/json


###
PUT http://localhost:3001/users/lk71IjZfFtBGNMxOrDqI6 HTTP/1.1
Content-Type: application/json

{
    "id": "lk71IjZfFtBGNMxOrDqI6",
    "name": "aaaaa",
    "email": "dddddddd",
    "position": "admin"
  }

###
DELETE  http://localhost:3001/users/MLrNY4a830EGYEZqL8uiW HTTP/1.1
Content-Type: application/json